# Generated by Django 3.2.8 on 2021-10-14 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='st_name',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='roll_num',
        ),
        migrations.RemoveField(
            model_name='student',
            name='standard',
        ),
    ]
